### ISSUE TITLE
Displaying image

### ISSUE THREAD

**Issue by MFernstrom** [alb42/MUIClass#1]
Hi alb, do you have an example for loading images?

I'm trying to load either images standalone like a TImage equivalent or in a grid

**Comment by alb42** [comment]
I added a simple [image example](https://github.com/alb42/MUIClass/blob/master/examples/ImageTest.pas) in alb42/MUIClass@f6a486a

If you need more sophisticated images you can use TMUIDrawPanel (Paintbox equivalent) and then draw using Datatypes or using the cybergraphics routines the image.

**Comment by MFernstrom** [comment]
Perfect! Thank you alb!
